// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261010121645_sa")]
    partial class sa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("BrandId");

                    b.HasIndex("BrandName")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "Nutri Mart Clean",
                            Country = "Việt Nam",
                            Description = "Thương hiệu độc quyền chuẩn Eat Clean Nutri Mart.",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Quaker",
                            Country = "Mỹ",
                            Description = "Thương hiệu yến mạch và ngũ cốc dinh dưỡng.",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "TH true MILK",
                            Country = "Việt Nam",
                            Description = "Thương hiệu sữa tươi và các sản phẩm từ sữa.",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Blue Diamond",
                            Country = "Mỹ",
                            Description = "Thương hiệu hạnh nhân và các sản phẩm từ hạt.",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 5,
                            BrandName = "Alsafi",
                            Country = "Campuchia",
                            Description = "Thương hiệu sữa hạt dinh dưỡng có nguồn gốc thực vật.",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 6,
                            BrandName = "Bertolli",
                            Country = "Ý",
                            Description = "Thương hiệu dầu oliu và gia vị cao cấp.",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 7,
                            BrandName = "Dalat Eco Organic",
                            Country = "Việt Nam",
                            Description = "Nông sản, rau củ quả tươi sạch đạt chuẩn VietGAP Đà Lạt.",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 8,
                            BrandName = "Eat Clean VN",
                            Country = "Việt Nam",
                            Description = "Sản phẩm đóng gói chuyên chế độ ăn Eat Clean.",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 9,
                            BrandName = "Dalat Green",
                            Country = "Việt Nam",
                            Description = "Trà thảo mộc và thức uống dinh dưỡng.",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 10,
                            BrandName = "Bee Gold",
                            Country = "Việt Nam",
                            Description = "Mật ong rừng nguyên chất và chế phẩm từ mật ong.",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 11,
                            BrandName = "Nutri Seed",
                            Country = "Việt Nam",
                            Description = "Superfood, hạt dinh dưỡng và bột sấy lạnh.",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 12,
                            BrandName = "Green Life Vegan",
                            Country = "Việt Nam",
                            Description = "Thực phẩm thuần chay và các chế phẩm thực vật.",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 13,
                            BrandName = "VietOrganic Natural",
                            Country = "Việt Nam",
                            Description = "Gia vị, gạo lứt và nông sản hữu cơ tự nhiên.",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 14,
                            BrandName = "Fresh Choice Seafood",
                            Country = "Việt Nam",
                            Description = "Cá hồi Na Uy và hải sản tươi sạch nhập khẩu.",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 15,
                            BrandName = "Nutri Snack Healthy",
                            Country = "Việt Nam",
                            Description = "Bánh ăn kiêng và snack lành mạnh Nutri Mart.",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Đặc sản miền Bắc",
                            Description = "Đặc sản Hà Nội, Hải Phòng, Quảng Ninh, Tây Bắc và các tỉnh phía Bắc."
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Đặc sản miền Trung",
                            Description = "Đặc sản Huế, Đà Nẵng, Quảng Nam, Bình Định và các tỉnh miền Trung."
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Đặc sản miền Nam",
                            Description = "Đặc sản miền Tây Nam Bộ, TP. Hồ Chí Minh và Đông Nam Bộ."
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Bánh kẹo truyền thống",
                            Description = "Bánh đậu xanh, bánh pía, kẹo dừa, bánh cốm và các loại bánh kẹo truyền thống."
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Đồ ăn vặt đóng gói",
                            Description = "Snack, bánh tráng, rong biển, đậu phộng và các món ăn vặt đóng gói."
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Khô bò, khô gà và thịt khô",
                            Description = "Khô bò, khô gà lá chanh, thịt trâu gác bếp và các loại thịt khô."
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Hải sản khô",
                            Description = "Mực khô, cá khô, tôm khô và các loại hải sản chế biến, bảo quản khô."
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Trái cây sấy",
                            Description = "Xoài sấy, mít sấy, chuối sấy, khoai lang sấy và trái cây sấy dẻo."
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Hạt và đậu ăn vặt",
                            Description = "Hạt điều, đậu phộng, hạt bí, hạt hướng dương và các loại hạt rang."
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Mứt và ô mai",
                            Description = "Ô mai Hà Nội, mứt gừng, mứt dừa, mứt trái cây và đặc sản ngày Tết."
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Nước chấm và gia vị vùng miền",
                            Description = "Nước mắm, mắm đặc sản, muối chấm, sa tế và các loại gia vị địa phương."
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Trà, cà phê và đồ uống",
                            Description = "Trà Thái Nguyên, cà phê Tây Nguyên, nước trái cây và đồ uống đặc sản."
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Mì, bún và thực phẩm khô",
                            Description = "Mì Quảng khô, bún khô, miến dong, bánh đa và các loại thực phẩm khô."
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Quà biếu đặc sản",
                            Description = "Hộp quà đặc sản vùng miền, giỏ quà bánh kẹo và sản phẩm cao cấp."
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Đặc sản đông lạnh",
                            Description = "Chả ram, nem chua, chả mực và các đặc sản cần bảo quản đông lạnh."
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "59 Nguyễn Thị Minh Khai, Phường Võ Thị Sáu, Quận 3, TP. Hồ Chí Minh",
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "120 Võ Văn Tần, Phường Võ Thị Sáu, Quận 3, TP. Hồ Chí Minh",
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "15 Lý Thường Kiệt, Phường 14, Quận 10, TP. Hồ Chí Minh",
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 10
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "12 Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh",
                            CustomerName = "Phạm Minh Tuấn",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0905123456",
                            RewardPoints = 180
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "45 Lê Lợi, Phường Bến Thành, Quận 1, TP. Hồ Chí Minh",
                            CustomerName = "Hoàng Thị Lan",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            RewardPoints = 75
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "8 Trần Hưng Đạo, Phường 6, Quận 5, TP. Hồ Chí Minh",
                            CustomerName = "Võ Quốc Bảo",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0937654321",
                            RewardPoints = 20
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "102 Điện Biên Phủ, Phường 17, Quận Bình Thạnh, TP. Hồ Chí Minh",
                            CustomerName = "Đặng Thu Hà",
                            MembershipRank = "Kim cương",
                            PhoneNumber = "0944556677",
                            RewardPoints = 520
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "36 Nguyễn Thị Thập, Phường Tân Quy, Quận 7, TP. Hồ Chí Minh",
                            CustomerName = "Bùi Anh Khoa",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0966778899",
                            RewardPoints = 5
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "27 Phan Văn Trị, Phường 10, Quận Gò Vấp, TP. Hồ Chí Minh",
                            CustomerName = "Ngô Thanh Mai",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0977889900",
                            RewardPoints = 90
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "63 Cách Mạng Tháng 8, Phường 12, Quận 10, TP. Hồ Chí Minh",
                            CustomerName = "Đỗ Hoài Nam",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0988990011",
                            RewardPoints = 210
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "210 Quang Trung, Phường 10, Quận Gò Vấp, TP. Hồ Chí Minh",
                            CustomerName = "Lý Gia Hân",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0399123456",
                            RewardPoints = 0
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "5 Võ Văn Ngân, Phường Linh Chiểu, TP. Thủ Đức, TP. Hồ Chí Minh",
                            CustomerName = "Trương Quốc Việt",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0868234567",
                            RewardPoints = 60
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "88 Nguyễn Oanh, Phường 17, Quận Gò Vấp, TP. Hồ Chí Minh",
                            CustomerName = "Nguyễn Minh Khôi",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0908765432",
                            RewardPoints = 230
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "156 Hoàng Diệu, Phường 6, Quận 4, TP. Hồ Chí Minh",
                            CustomerName = "Phan Ngọc Anh",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0938123456",
                            RewardPoints = 85
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "72 Kha Vạn Cân, Phường Hiệp Bình Chánh, TP. Thủ Đức, TP. Hồ Chí Minh",
                            CustomerName = "Đinh Thanh Tùng",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0976234518",
                            RewardPoints = 15
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CashierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CashierId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CashierId = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Discount = 0m,
                            OrderCode = "HD0001",
                            PaymentMethod = "CASH",
                            Status = "PAID",
                            Subtotal = 82000m,
                            Total = 82000m
                        },
                        new
                        {
                            OrderId = 2,
                            CashierId = 4,
                            CreatedAt = new DateTime(2026, 9, 2, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Discount = 10000m,
                            OrderCode = "HD0002",
                            PaymentMethod = "MOMO",
                            Status = "PAID",
                            Subtotal = 221000m,
                            Total = 211000m
                        },
                        new
                        {
                            OrderId = 3,
                            CashierId = 5,
                            CreatedAt = new DateTime(2026, 9, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 6,
                            Discount = 0m,
                            OrderCode = "HD0003",
                            PaymentMethod = "CASH",
                            Status = "PAID",
                            Subtotal = 173000m,
                            Total = 173000m
                        },
                        new
                        {
                            OrderId = 4,
                            CashierId = 5,
                            CreatedAt = new DateTime(2026, 9, 4, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 7,
                            Discount = 20000m,
                            OrderCode = "HD0004",
                            PaymentMethod = "CARD",
                            Status = "PAID",
                            Subtotal = 400000m,
                            Total = 380000m
                        },
                        new
                        {
                            OrderId = 5,
                            CashierId = 6,
                            CreatedAt = new DateTime(2026, 9, 5, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            Discount = 23000m,
                            OrderCode = "HD0005",
                            PaymentMethod = "BANK_TRANSFER",
                            Status = "PAID",
                            Subtotal = 467000m,
                            Total = 444000m
                        },
                        new
                        {
                            OrderId = 6,
                            CashierId = 6,
                            CreatedAt = new DateTime(2026, 9, 6, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 8,
                            Discount = 0m,
                            OrderCode = "HD0006",
                            PaymentMethod = "CASH",
                            Status = "PAID",
                            Subtotal = 158000m,
                            Total = 158000m
                        },
                        new
                        {
                            OrderId = 7,
                            CashierId = 7,
                            CreatedAt = new DateTime(2026, 9, 7, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            Discount = 0m,
                            OrderCode = "HD0007",
                            PaymentMethod = "CASH",
                            Status = "PAID",
                            Subtotal = 126000m,
                            Total = 126000m
                        },
                        new
                        {
                            OrderId = 8,
                            CashierId = 7,
                            CreatedAt = new DateTime(2026, 9, 8, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 10,
                            Discount = 12000m,
                            OrderCode = "HD0008",
                            PaymentMethod = "MOMO",
                            Status = "PAID",
                            Subtotal = 237000m,
                            Total = 225000m
                        },
                        new
                        {
                            OrderId = 9,
                            CashierId = 8,
                            CreatedAt = new DateTime(2026, 9, 9, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            Discount = 0m,
                            OrderCode = "HD0009",
                            PaymentMethod = "CARD",
                            Status = "PAID",
                            Subtotal = 151000m,
                            Total = 151000m
                        },
                        new
                        {
                            OrderId = 10,
                            CashierId = 8,
                            CreatedAt = new DateTime(2026, 9, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 11,
                            Discount = 0m,
                            OrderCode = "HD0010",
                            PaymentMethod = "CASH",
                            Status = "CANCELLED",
                            Subtotal = 129000m,
                            Total = 129000m
                        },
                        new
                        {
                            OrderId = 11,
                            CashierId = 9,
                            CreatedAt = new DateTime(2026, 9, 11, 15, 25, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 9,
                            Discount = 12000m,
                            OrderCode = "HD0011",
                            PaymentMethod = "BANK_TRANSFER",
                            Status = "PAID",
                            Subtotal = 262000m,
                            Total = 250000m
                        },
                        new
                        {
                            OrderId = 12,
                            CashierId = 9,
                            CreatedAt = new DateTime(2026, 9, 12, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 12,
                            Discount = 0m,
                            OrderCode = "HD0012",
                            PaymentMethod = "MOMO",
                            Status = "PAID",
                            Subtotal = 258000m,
                            Total = 258000m
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderItemId = 1,
                            LineTotal = 50000m,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 25000m
                        },
                        new
                        {
                            OrderItemId = 2,
                            LineTotal = 32000m,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 32000m
                        },
                        new
                        {
                            OrderItemId = 3,
                            LineTotal = 65000m,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 65000m
                        },
                        new
                        {
                            OrderItemId = 4,
                            LineTotal = 156000m,
                            OrderId = 2,
                            ProductId = 5,
                            Quantity = 2,
                            UnitPrice = 78000m
                        },
                        new
                        {
                            OrderItemId = 5,
                            LineTotal = 89000m,
                            OrderId = 3,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 89000m
                        },
                        new
                        {
                            OrderItemId = 6,
                            LineTotal = 84000m,
                            OrderId = 3,
                            ProductId = 8,
                            Quantity = 2,
                            UnitPrice = 42000m
                        },
                        new
                        {
                            OrderItemId = 7,
                            LineTotal = 145000m,
                            OrderId = 4,
                            ProductId = 9,
                            Quantity = 1,
                            UnitPrice = 145000m
                        },
                        new
                        {
                            OrderItemId = 8,
                            LineTotal = 120000m,
                            OrderId = 4,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 120000m
                        },
                        new
                        {
                            OrderItemId = 9,
                            LineTotal = 135000m,
                            OrderId = 4,
                            ProductId = 17,
                            Quantity = 1,
                            UnitPrice = 135000m
                        },
                        new
                        {
                            OrderItemId = 10,
                            LineTotal = 338000m,
                            OrderId = 5,
                            ProductId = 12,
                            Quantity = 2,
                            UnitPrice = 169000m
                        },
                        new
                        {
                            OrderItemId = 11,
                            LineTotal = 129000m,
                            OrderId = 5,
                            ProductId = 11,
                            Quantity = 1,
                            UnitPrice = 129000m
                        },
                        new
                        {
                            OrderItemId = 12,
                            LineTotal = 104000m,
                            OrderId = 6,
                            ProductId = 13,
                            Quantity = 2,
                            UnitPrice = 52000m
                        },
                        new
                        {
                            OrderItemId = 13,
                            LineTotal = 54000m,
                            OrderId = 6,
                            ProductId = 16,
                            Quantity = 3,
                            UnitPrice = 18000m
                        },
                        new
                        {
                            OrderItemId = 14,
                            LineTotal = 48000m,
                            OrderId = 7,
                            ProductId = 14,
                            Quantity = 1,
                            UnitPrice = 48000m
                        },
                        new
                        {
                            OrderItemId = 15,
                            LineTotal = 78000m,
                            OrderId = 7,
                            ProductId = 15,
                            Quantity = 2,
                            UnitPrice = 39000m
                        },
                        new
                        {
                            OrderItemId = 16,
                            LineTotal = 95000m,
                            OrderId = 8,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 95000m
                        },
                        new
                        {
                            OrderItemId = 17,
                            LineTotal = 110000m,
                            OrderId = 8,
                            ProductId = 6,
                            Quantity = 2,
                            UnitPrice = 55000m
                        },
                        new
                        {
                            OrderItemId = 18,
                            LineTotal = 32000m,
                            OrderId = 8,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 32000m
                        },
                        new
                        {
                            OrderItemId = 19,
                            LineTotal = 126000m,
                            OrderId = 9,
                            ProductId = 8,
                            Quantity = 3,
                            UnitPrice = 42000m
                        },
                        new
                        {
                            OrderItemId = 20,
                            LineTotal = 25000m,
                            OrderId = 9,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 25000m
                        },
                        new
                        {
                            OrderItemId = 21,
                            LineTotal = 129000m,
                            OrderId = 10,
                            ProductId = 11,
                            Quantity = 1,
                            UnitPrice = 129000m
                        },
                        new
                        {
                            OrderItemId = 22,
                            LineTotal = 130000m,
                            OrderId = 11,
                            ProductId = 3,
                            Quantity = 2,
                            UnitPrice = 65000m
                        },
                        new
                        {
                            OrderItemId = 23,
                            LineTotal = 96000m,
                            OrderId = 11,
                            ProductId = 14,
                            Quantity = 2,
                            UnitPrice = 48000m
                        },
                        new
                        {
                            OrderItemId = 24,
                            LineTotal = 36000m,
                            OrderId = 11,
                            ProductId = 16,
                            Quantity = 2,
                            UnitPrice = 18000m
                        },
                        new
                        {
                            OrderItemId = 25,
                            LineTotal = 89000m,
                            OrderId = 12,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 89000m
                        },
                        new
                        {
                            OrderItemId = 26,
                            LineTotal = 169000m,
                            OrderId = 12,
                            ProductId = 12,
                            Quantity = 1,
                            UnitPrice = 169000m
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProductId");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8938501234561",
                            BrandId = 3,
                            CategoryId = 4,
                            CostPrice = 32000m,
                            IsActive = true,
                            Price = 45000m,
                            ProductName = "Bánh đậu xanh Hải Dương 200g",
                            StockQuantity = 80,
                            SupplierId = 2,
                            Unit = "hộp"
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8938501234562",
                            BrandId = 15,
                            CategoryId = 5,
                            CostPrice = 18000m,
                            IsActive = true,
                            Price = 28000m,
                            ProductName = "Bánh tráng muối Tây Ninh 250g",
                            StockQuantity = 120,
                            SupplierId = 6,
                            Unit = "gói"
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8938501234563",
                            BrandId = 1,
                            CategoryId = 6,
                            CostPrice = 85000m,
                            IsActive = true,
                            Price = 115000m,
                            ProductName = "Khô bò miếng đặc biệt 200g",
                            StockQuantity = 35,
                            SupplierId = 1,
                            Unit = "gói"
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8938501234564",
                            BrandId = 1,
                            CategoryId = 7,
                            CostPrice = 145000m,
                            IsActive = true,
                            Price = 185000m,
                            ProductName = "Mực khô loại ngon 250g",
                            StockQuantity = 25,
                            SupplierId = 7,
                            Unit = "gói"
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8938501234565",
                            BrandId = 8,
                            CategoryId = 8,
                            CostPrice = 45000m,
                            IsActive = true,
                            Price = 65000m,
                            ProductName = "Xoài sấy dẻo 250g",
                            StockQuantity = 60,
                            SupplierId = 9,
                            Unit = "gói"
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8938501234566",
                            BrandId = 4,
                            CategoryId = 9,
                            CostPrice = 70000m,
                            IsActive = true,
                            Price = 95000m,
                            ProductName = "Hạt điều rang muối 300g",
                            StockQuantity = 50,
                            SupplierId = 10,
                            Unit = "hộp"
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8938501234567",
                            BrandId = 14,
                            CategoryId = 4,
                            CostPrice = 28000m,
                            IsActive = true,
                            Price = 42000m,
                            ProductName = "Kẹo dừa Bến Tre 300g",
                            StockQuantity = 90,
                            SupplierId = 14,
                            Unit = "gói"
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8938501234568",
                            BrandId = 7,
                            CategoryId = 10,
                            CostPrice = 37000m,
                            IsActive = true,
                            Price = 55000m,
                            ProductName = "Ô mai mơ Hà Nội 200g",
                            StockQuantity = 45,
                            SupplierId = 3,
                            Unit = "hộp"
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8938501234569",
                            BrandId = 6,
                            CategoryId = 11,
                            CostPrice = 15000m,
                            IsActive = true,
                            Price = 25000m,
                            ProductName = "Muối tôm Tây Ninh 100g",
                            StockQuantity = 100,
                            SupplierId = 6,
                            Unit = "hũ"
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8938501234570",
                            BrandId = 11,
                            CategoryId = 12,
                            CostPrice = 90000m,
                            IsActive = true,
                            Price = 125000m,
                            ProductName = "Cà phê rang xay Tây Nguyên 500g",
                            StockQuantity = 40,
                            SupplierId = 12,
                            Unit = "gói"
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8938501234571",
                            BrandId = 12,
                            CategoryId = 12,
                            CostPrice = 60000m,
                            IsActive = true,
                            Price = 85000m,
                            ProductName = "Trà Thái Nguyên đặc sản 200g",
                            StockQuantity = 55,
                            SupplierId = 13,
                            Unit = "gói"
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8938501234572",
                            BrandId = 14,
                            CategoryId = 4,
                            CostPrice = 55000m,
                            IsActive = true,
                            Price = 78000m,
                            ProductName = "Bánh pía sầu riêng 4 bánh",
                            StockQuantity = 40,
                            SupplierId = 14,
                            Unit = "hộp"
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8938501234573",
                            BrandId = 13,
                            CategoryId = 13,
                            CostPrice = 35000m,
                            IsActive = true,
                            Price = 52000m,
                            ProductName = "Bánh phồng tôm 500g",
                            StockQuantity = 65,
                            SupplierId = 14,
                            Unit = "gói"
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8938501234574",
                            BrandId = 9,
                            CategoryId = 8,
                            CostPrice = 25000m,
                            IsActive = true,
                            Price = 38000m,
                            ProductName = "Chuối sấy giòn 200g",
                            StockQuantity = 75,
                            SupplierId = 11,
                            Unit = "gói"
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8938501234575",
                            BrandId = 10,
                            CategoryId = 6,
                            CostPrice = 47000m,
                            IsActive = true,
                            Price = 68000m,
                            ProductName = "Khô gà lá chanh 250g",
                            StockQuantity = 50,
                            SupplierId = 15,
                            Unit = "hũ"
                        },
                        new
                        {
                            ProductId = 16,
                            Barcode = "8938501234576",
                            BrandId = 4,
                            CategoryId = 9,
                            CostPrice = 20000m,
                            IsActive = true,
                            Price = 32000m,
                            ProductName = "Đậu phộng rang tỏi ớt 200g",
                            StockQuantity = 85,
                            SupplierId = 15,
                            Unit = "gói"
                        },
                        new
                        {
                            ProductId = 17,
                            Barcode = "8938501234577",
                            BrandId = 1,
                            CategoryId = 14,
                            CostPrice = 270000m,
                            IsActive = true,
                            Price = 350000m,
                            ProductName = "Hộp quà đặc sản ba miền",
                            StockQuantity = 15,
                            SupplierId = 15,
                            Unit = "hộp"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "ADMIN"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "WAREHOUSE"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "CASHIER"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            Address = "TP. Sơn La, tỉnh Sơn La",
                            Email = "lienhe.dacsantaybac@gmail.com",
                            PhoneNumber = "02123812345",
                            SupplierName = "Công ty Đặc sản Tây Bắc Việt"
                        },
                        new
                        {
                            SupplierId = 2,
                            Address = "TP. Hải Dương, tỉnh Hải Dương",
                            Email = "banhang.banhdauxanh@gmail.com",
                            PhoneNumber = "02203812345",
                            SupplierName = "Cơ sở Bánh đậu xanh Hải Dương"
                        },
                        new
                        {
                            SupplierId = 3,
                            Address = "Quận Hoàn Kiếm, Hà Nội",
                            Email = "kinhdoanh.omaihanoi@gmail.com",
                            PhoneNumber = "02433812345",
                            SupplierName = "Cơ sở Ô mai Hà Nội"
                        },
                        new
                        {
                            SupplierId = 4,
                            Address = "TP. Huế, thành phố Huế",
                            Email = "sales.dacsanhue@gmail.com",
                            PhoneNumber = "02343812345",
                            SupplierName = "Công ty Đặc sản Huế"
                        },
                        new
                        {
                            SupplierId = 5,
                            Address = "TP. Hội An, thành phố Đà Nẵng",
                            Email = "lienhe.dacsanquangnam@gmail.com",
                            PhoneNumber = "02353812345",
                            SupplierName = "Công ty Đặc sản Quảng Nam"
                        },
                        new
                        {
                            SupplierId = 6,
                            Address = "TP. Tây Ninh, tỉnh Tây Ninh",
                            Email = "banhang.banhtrangtn@gmail.com",
                            PhoneNumber = "02763812345",
                            SupplierName = "Cơ sở Bánh tráng Tây Ninh"
                        },
                        new
                        {
                            SupplierId = 7,
                            Address = "TP. Quy Nhơn, tỉnh Gia Lai",
                            Email = "sales.haisanmientrung@gmail.com",
                            PhoneNumber = "02563812345",
                            SupplierName = "Công ty Hải sản khô miền Trung"
                        },
                        new
                        {
                            SupplierId = 8,
                            Address = "TP. Rạch Giá, tỉnh An Giang",
                            Email = "lienhe.khocamientay@gmail.com",
                            PhoneNumber = "02973812345",
                            SupplierName = "Cơ sở Khô cá miền Tây"
                        },
                        new
                        {
                            SupplierId = 9,
                            Address = "TP. Bến Cát, TP. Hồ Chí Minh",
                            Email = "sales.traicaysay@gmail.com",
                            PhoneNumber = "02743812345",
                            SupplierName = "Công ty Trái cây sấy Việt"
                        },
                        new
                        {
                            SupplierId = 10,
                            Address = "Đồng Xoài, tỉnh Đồng Nai",
                            Email = "order.hatdieubp@gmail.com",
                            PhoneNumber = "02713812345",
                            SupplierName = "Cơ sở Hạt điều Bình Phước"
                        },
                        new
                        {
                            SupplierId = 11,
                            Address = "Đà Lạt, tỉnh Lâm Đồng",
                            Email = "sales.dacsandalat@gmail.com",
                            PhoneNumber = "02633812345",
                            SupplierName = "Công ty Đặc sản Đà Lạt"
                        },
                        new
                        {
                            SupplierId = 12,
                            Address = "TP. Buôn Ma Thuột, tỉnh Đắk Lắk",
                            Email = "kinhdoanh.caphetaynguyen@gmail.com",
                            PhoneNumber = "02623812345",
                            SupplierName = "Công ty Cà phê Tây Nguyên"
                        },
                        new
                        {
                            SupplierId = 13,
                            Address = "TP. Thái Nguyên, tỉnh Thái Nguyên",
                            Email = "lienhe.trathainguyen@gmail.com",
                            PhoneNumber = "02083812345",
                            SupplierName = "Hợp tác xã Trà Thái Nguyên"
                        },
                        new
                        {
                            SupplierId = 14,
                            Address = "TP. Cần Thơ",
                            Email = "sales.dacsanmientay@gmail.com",
                            PhoneNumber = "02923812345",
                            SupplierName = "Công ty Đặc sản miền Tây"
                        },
                        new
                        {
                            SupplierId = 15,
                            Address = "TP. Hồ Chí Minh",
                            Email = "phanphoi.dacsanviet@gmail.com",
                            PhoneNumber = "02833812345",
                            SupplierName = "Công ty Phân phối Đặc sản Việt"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            FullName = "Quản trị hệ thống",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000001",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 1, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "warehouse01@gmail.com",
                            FullName = "Nguyễn Thị Mai",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000002",
                            RoleId = 2,
                            Username = "warehouse01"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 1, 6, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "warehouse02@gmail.com",
                            FullName = "Trần Văn Điều",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000003",
                            RoleId = 2,
                            Username = "warehouse02"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2026, 2, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier01@gmail.com",
                            FullName = "Lê Thị Thu Ngân",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000004",
                            RoleId = 3,
                            Username = "cashier01"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2026, 2, 1, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier02@gmail.com",
                            FullName = "Phạm Văn Ngân",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000005",
                            RoleId = 3,
                            Username = "cashier02"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2026, 2, 1, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier03@gmail.com",
                            FullName = "Hoàng Thị Ngân",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000006",
                            RoleId = 3,
                            Username = "cashier03"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2026, 2, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier04@gmail.com",
                            FullName = "Võ Minh Ngân",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000007",
                            RoleId = 3,
                            Username = "cashier04"
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2026, 2, 10, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier05@gmail.com",
                            FullName = "Đặng ThịNgân",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000008",
                            RoleId = 3,
                            Username = "cashier05"
                        },
                        new
                        {
                            UserId = 9,
                            CreatedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier06@gmail.com",
                            FullName = "Bùi Văn Ngân",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000009",
                            RoleId = 3,
                            Username = "cashier06"
                        },
                        new
                        {
                            UserId = 10,
                            CreatedAt = new DateTime(2026, 3, 1, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier07@gmail.com",
                            FullName = "Ngô Thị Thu Ngân",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000010",
                            RoleId = 3,
                            Username = "cashier07"
                        },
                        new
                        {
                            UserId = 11,
                            CreatedAt = new DateTime(2026, 4, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier08@gmail.com",
                            FullName = "Đỗ Văn Ngân",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000011",
                            RoleId = 3,
                            Username = "cashier08"
                        },
                        new
                        {
                            UserId = 12,
                            CreatedAt = new DateTime(2026, 4, 1, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier09@gmail.com",
                            FullName = "Lý Thị Thu Ngân",
                            IsActive = false,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000012",
                            RoleId = 3,
                            Username = "cashier09"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.User", "Cashier")
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cashier");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.OrderItem", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.RefreshToken", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.User", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
