// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261003112206_001")]
    partial class _001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "Nutri Mart Clean",
                            Description = "Thương hiệu độc quyền chuẩn Eat Clean Nutri Mart"
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Dalat Eco Organic",
                            Description = "Rau củ quả tươi sạch đạt chứng nhận VietGAP/GlobalGAP"
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "VietOrganic Natural",
                            Description = "Gia vị và dầu ăn thực vật hữu cơ tự nhiên"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Rau củ quả hữu cơ",
                            Description = "Rau xanh, củ quả tươi đạt chuẩn Organic, VietGAP"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Ngũ cốc & Hạt dinh dưỡng",
                            Description = "Yến mạch, hạt chia, hạnh nhân, óc chó, mác ca"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa hạt & Sữa chua hữu cơ",
                            Description = "Sữa hạnh nhân, sữa đậu nành, sữa chua Hy Lạp"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Thực phẩm Eat Clean",
                            Description = "Ức gà, cơm gạo lứt, salad đóng gói ăn liền"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị & Dầu thực vật tự nhiên",
                            Description = "Dầu oliu, mật ong nguyên chất, muối hồng Himalaya"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Trái cây tươi xuất nhập khẩu",
                            Description = "Táo Envy, dâu tây Đà Lạt, việt quất, cam vàng"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Trà & Thức uống thực dưỡng",
                            Description = "Trà dưỡng nhan, kombucha, trà xanh matcha, nước ép tươi"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Đồ khô & Bánh ăn kiêng",
                            Description = "Bánh biscotti, thanh hạt năng lượng, bún chùm ngây, mì gạo lứt"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Thịt & Hải sản tươi sạch",
                            Description = "Thịt heo ăn chay, cá hồi măng tây, tôm sinh thái"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Thực phẩm đông lạnh hữu cơ",
                            Description = "Rau củ hỗn hợp đông lạnh, chả chay organic, dumpling thực dưỡng"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Bánh kẹo & Snack Healthy",
                            Description = "Snack chuối sấy lạnh, kẹo dẻo vitamin, rong biển sấy giòn"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Thực phẩm bổ sung & Detox",
                            Description = "Bột cần tây sấy lạnh, bột chlorella, collagen thực vật"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Nước ép & Smoothie đóng chai",
                            Description = "Nước ép cần tây củ dền, smoothie bơ chuối, nước dừa tươi"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Gạo & Các loại đậu hữu cơ",
                            Description = "Gạo lứt đỏ, gạo st25 organic, đậu đen xanh lòng, đậu chickpea"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Sản phẩm thuần chay (Vegan)",
                            Description = "Pate thuần chay, giò nấm, nước mắm chay cốt đậu nành"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "123 Lê Lợi, Q.1, TP.HCM",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nam.nguyen@gmail.com",
                            FullName = "Nguyễn Hoàng Nam",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0987654321",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "456 Nguyễn Thị Minh Khai, Q.3, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mai.pham@gmail.com",
                            FullName = "Phạm Thị Mai",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0978123456",
                            RewardPoints = 520
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "789 Điện Biên Phủ, Q.Bình Thạnh, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "minh.tran@gmail.com",
                            FullName = "Trần Văn Minh",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0912345678",
                            RewardPoints = 1200
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "12 Trần Hưng Đạo, Q.5, TP.HCM",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thanh.le@gmail.com",
                            FullName = "Lê Thị Thanh",
                            MembershipRank = "Đồng",
                            PhoneNumber = "0903112233",
                            RewardPoints = 45
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "88 Nguyễn Trãi, Q.5, TP.HCM",
                            CreatedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tuan.hoang@gmail.com",
                            FullName = "Hoàng Anh Tuấn",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0934556677",
                            RewardPoints = 230
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "15 Nguyễn Đình Chiểu, Q.3, TP.HCM",
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thao.dang@gmail.com",
                            FullName = "Đặng Thu Thảo",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0967889900",
                            RewardPoints = 680
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "102 Cách Mạng Tháng 8, Q.10, TP.HCM",
                            CreatedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bao.vu@gmail.com",
                            FullName = "Vũ Quốc Bảo",
                            MembershipRank = "Đồng",
                            PhoneNumber = "0981122334",
                            RewardPoints = 80
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "234 Phan Xích Long, Q.Phú Nhuận, TP.HCM",
                            CreatedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ngoc.bui@gmail.com",
                            FullName = "Bùi Thị Ngọc",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0945667788",
                            RewardPoints = 310
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "56 Võ Văn Tần, Q.3, TP.HCM",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khoa.do@gmail.com",
                            FullName = "Đỗ Duy Khoa",
                            MembershipRank = "Đồng",
                            PhoneNumber = "0922334455",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "77 Hoàng Văn Thụ, Q.Phú Nhuận, TP.HCM",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "phuong.ngo@gmail.com",
                            FullName = "Ngô Bích Phương",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0918776655",
                            RewardPoints = 950
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "301 Lý Thường Kiệt, Q.11, TP.HCM",
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "linh.duong@gmail.com",
                            FullName = "Dương Khánh Linh",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0938990011",
                            RewardPoints = 110
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "45 Lê Văn Sỹ, Q.3, TP.HCM",
                            CreatedAt = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "triet.ly@gmail.com",
                            FullName = "Lý Minh Triết",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0971223344",
                            RewardPoints = 1500
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "89 Nam Kỳ Khởi Nghĩa, Q.1, TP.HCM",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thuong.phan@gmail.com",
                            FullName = "Phan Hoài Thương",
                            MembershipRank = "Đồng",
                            PhoneNumber = "0908771122",
                            RewardPoints = 60
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "142 Phạm Văn Đồng, Q.Thủ Đức, TP.HCM",
                            CreatedAt = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "truong.trinh@gmail.com",
                            FullName = "Trịnh Xuân Trường",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0961445566",
                            RewardPoints = 420
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "67 Cộng Hòa, Q.Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nhi.vo@gmail.com",
                            FullName = "Võ Tuyết Nhi",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0949887766",
                            RewardPoints = 880
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 143000m,
                            UserId = 2
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 3, 2, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 120000m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderItemId = 1,
                            OrderId = 1,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 65000m
                        },
                        new
                        {
                            OrderItemId = 2,
                            OrderId = 1,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 78000m
                        },
                        new
                        {
                            OrderItemId = 3,
                            OrderId = 2,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 120000m
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8938501234561",
                            BrandId = 2,
                            CategoryId = 1,
                            Price = 25000m,
                            ProductName = "Rau cải bó xôi hữu cơ 300g",
                            StockQuantity = 30,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8938501234562",
                            BrandId = 2,
                            CategoryId = 1,
                            Price = 32000m,
                            ProductName = "Cà chua bí đỏ hữu cơ 500g",
                            StockQuantity = 40,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8938501234563",
                            BrandId = 2,
                            CategoryId = 1,
                            Price = 45000m,
                            ProductName = "Bông cải xanh Đà Lạt Organic 500g",
                            StockQuantity = 25,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8938501234564",
                            BrandId = 1,
                            CategoryId = 2,
                            Price = 65000m,
                            ProductName = "Yến mạch nguyên hạt Quaker 500g",
                            StockQuantity = 30,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8938501234565",
                            BrandId = 1,
                            CategoryId = 2,
                            Price = 95000m,
                            ProductName = "Hạt hạnh nhân rang Mỹ 250g",
                            StockQuantity = 25,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8938501234566",
                            BrandId = 1,
                            CategoryId = 2,
                            Price = 75000m,
                            ProductName = "Hạt chia hữu cơ Úc 200g",
                            StockQuantity = 35,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8938501234567",
                            BrandId = 1,
                            CategoryId = 3,
                            Price = 78000m,
                            ProductName = "Sữa hạnh nhân Nutri 1L",
                            StockQuantity = 15,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8938501234568",
                            BrandId = 1,
                            CategoryId = 3,
                            Price = 55000m,
                            ProductName = "Sữa chua Hy Lạp không đường 500g",
                            StockQuantity = 20,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8938501234569",
                            BrandId = 1,
                            CategoryId = 3,
                            Price = 42000m,
                            ProductName = "Sữa đậu nành hữu cơ 1L",
                            StockQuantity = 30,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8938501234570",
                            BrandId = 1,
                            CategoryId = 4,
                            Price = 89000m,
                            ProductName = "Ức gà tươi đông lạnh 1kg",
                            StockQuantity = 50,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8938501234571",
                            BrandId = 1,
                            CategoryId = 4,
                            Price = 42000m,
                            ProductName = "Cơm gạo lứt đóng hộp ăn liền 250g",
                            StockQuantity = 45,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8938501234572",
                            BrandId = 1,
                            CategoryId = 4,
                            Price = 48000m,
                            ProductName = "Salad ức gà xốt chanh dây đóng gói 200g",
                            StockQuantity = 18,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8938501234573",
                            BrandId = 3,
                            CategoryId = 5,
                            Price = 145000m,
                            ProductName = "Dầu oliu nguyên chất Extra Virgin 500ml",
                            StockQuantity = 20,
                            SupplierId = 3
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8938501234574",
                            BrandId = 3,
                            CategoryId = 5,
                            Price = 120000m,
                            ProductName = "Mật ong hoa rừng nguyên chất 350ml",
                            StockQuantity = 18,
                            SupplierId = 3
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8938501234575",
                            BrandId = 3,
                            CategoryId = 5,
                            Price = 38000m,
                            ProductName = "Muối hồng Himalaya nguyên chất 500g",
                            StockQuantity = 40,
                            SupplierId = 3
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Quản trị viên (Toàn quyền quản lý kho, nhập hàng, nhân sự và báo cáo doanh thu POS)",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Nhân viên bán hàng / POS (Quét mã vạch, lập hóa đơn, tích điểm khách hàng)",
                            RoleName = "Thu Ngân"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Tài khoản khách hàng (Tra cứu điểm thưởng, hạng thành viên, lịch sử mua hàng)",
                            RoleName = "Khách Hàng"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            Address = "Phường 11, TP. Đà Lạt, Lâm Đồng",
                            ContactName = "Nguyễn Văn An",
                            PhoneNumber = "0901234567",
                            SupplierName = "Nông Trại Xanh Dalat Organic Farm"
                        },
                        new
                        {
                            SupplierId = 2,
                            Address = "KCN Tân Bình, Tân Phú, TP.HCM",
                            ContactName = "Trần Thị Bích",
                            PhoneNumber = "0912345678",
                            SupplierName = "Công ty TNHH Thực Phẩm Sạch NutriLife"
                        },
                        new
                        {
                            SupplierId = 3,
                            Address = "Huyện Củ Chi, TP.HCM",
                            ContactName = "Lê Văn Cường",
                            PhoneNumber = "0923456789",
                            SupplierName = "Hợp Tác Xã Gia Vị & Nông Sản Việt"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FullName = "Quản Lý Nutri Mart",
                            PasswordHash = "admin123",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            FullName = "Thu Ngân Ca Sáng (Nguyễn Thu Hà)",
                            PasswordHash = "123456",
                            RoleId = 2,
                            Username = "thungan01"
                        },
                        new
                        {
                            UserId = 3,
                            FullName = "Thu Ngân Ca Chiều (Lê Hoàng Nam)",
                            PasswordHash = "123456",
                            RoleId = 2,
                            Username = "thungan02"
                        },
                        new
                        {
                            UserId = 4,
                            FullName = "Nguyễn Hoàng Nam",
                            PasswordHash = "123456",
                            RoleId = 3,
                            Username = "khachhang01"
                        },
                        new
                        {
                            UserId = 5,
                            FullName = "Phạm Thị Mai",
                            PasswordHash = "123456",
                            RoleId = 3,
                            Username = "khachhang02"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.HasOne("MiniSupermarket.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.OrderItem", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId");

                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.RefreshToken", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.User", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
